name: Continuous Integration
on:
  push:
    branches:
      - main
      - actions-*
    tags:
      - v*
  pull_request:
    branches-ignore:
      - actions-*
  workflow_dispatch:

jobs:
  specs:
    name: Run specs
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: "ruby"
            standardrb: true
          - ruby: "4.0"
            appraisal: "activerecord_8.1"
          - ruby: "3.4"
            appraisal: "activerecord_8.0"
          - ruby: "3.3"
            appraisal: "activerecord_7.2"
          - ruby: "3.2"
            appraisal: "activerecord_7.1"
          - ruby: "3.1"
            appraisal: "activerecord_7.0"
          - ruby: "3.0"
            appraisal: "activerecord_6.1"
          - ruby: "2.7"
            appraisal: "activerecord_6.0"
          - ruby: "2.6"
            appraisal: "activerecord_5.2"
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Ruby CI
        uses: bdurand/github-actions/ruby-ci@b7560883d5f8557f5d69fe8bd82721bbb5ed76df # v1.0.4
        with:
          ruby: ${{ matrix.ruby }}
          appraisal: ${{ matrix.appraisal }}
          bundler: ${{ matrix.bundler }}
          standardrb: ${{ matrix.standardrb }}
          yard: ${{ matrix.yard }}
          frozen_strings: ${{ matrix.frozen_strings }}
